### ISSUE TITLE
[Feat] Show "last updated"

### ISSUE THREAD

**Issue by davipt** [vostpt/greve-transportes-perigosos#163] opened 2019-08-13 11:43 UTC
On "Consultar", it would be nice to see the time of the last-updated so we know how state is the information of the status of a fuel station.

there seems to be timestamps on the DB, and on app/Http/Controllers/CacheController.php it should be possible to write the updated timestamp on the cache.JSON file, on the line
 $json = FuelStation::all('id', 'name', 'brand', 'long', 'lat', 'repa', 'sell_gasoline', 'sell_diesel', 'sell_lpg', 'has_gasoline', 'has_diesel', 'has_lpg')->toJson();
and then adapt the html+javascript to show the date on the box of the fuel station status

**Comment by miguelantoniosantos** [comment] 2019-08-13 11:55
Duplicate of #134

**Closed as completed by miguelantoniosantos** 2019-08-13 11:55 UTC
